version: 2

jobs:
  commitlint:
    docker:
      - image: secretbase/circleci-commitlint:latest
    working_directory: /www
    environment:
      CIRCLE_COMPARE_URL: << pipeline.project.git_url >>/compare/<< pipeline.git.base_revision >>..<<pipeline.git.revision>>
    steps:
      - checkout
      - run:
          name: Lint commit messages
          command: |
            /bin/sh /.scripts/commitlint_range.sh

workflows:
  version: 2
  my_pipeline:
    jobs:
      - commitlint
